### ISSUE TITLE
value 的输出根据选择顺序来。

### ISSUE THREAD

**Issue by eternalsky** [uxcore/uxcore-multi-select#8]
目前 value 的输出是根据 option 的顺序来的，这对于一些对顺序上有要求的业务不太方便，可以改成 value 输出按照 选择的顺序来。

**Comment by gbk** [comment]
直接改成按选择的顺序来？需求上确认 OK 么？

**Comment by eternalsky** [comment]
恩，来自用户的一些反馈，而且这样的话，和 Select 的逻辑也能保持一致了，Select 就是有顺序的~

**Comment by gbk** [comment]
OK
